version: 2.1
jobs:
  pkg-install:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      # Cached build dependencies
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}
            - deps
      - run:
          name: Package installation
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -e .
      - save_cache:
          paths:
            - ./venv
          key: deps-{{ checksum "requirements.txt" }}
  pkg-test:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      # Cached test dependencies
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}
            - deps-{{ checksum "requirements.txt" }}
            - deps
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -e .
            pip install -r .circleci/requirements.txt
      - save_cache:
          when: always
          paths:
            - ./venv
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}
      - run:
          name: Package unit tests
          command: |
            . venv/bin/activate
            coverage run -m pytest discover test/
  flake8-py3:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install flake8
      - run:
          name: Run flake8
          command: |
            flake8 --version
            flake8 ./
  mypy-py3:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}
            - deps
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -e . --upgrade
            pip install mypy
      - run:
          name: Run mypy
          command: |
            mypy --version
            mypy --config-file mypy.ini

  mypy-py3:
    runs-on: ubuntu-latest
    needs: pkg-install
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Cache python modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ hashFiles('requirements.txt') }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pkg-deps-${{ hashFiles('requirements.txt') }}-
            ${{ runner.os }}-pkg-deps-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . --upgrade
          pip install mypy
      - name: Run mypy
        run: |
          mypy --version
          mypy --config-file mypy.ini

workflows:
  version: 2.1
  python-package:
    jobs:
      - pkg-install
      - pkg-test:
          requires:
            - pkg-install
      - flake8-py3:
          requires:
            - pkg-install
      - mypy-py3:
          requires:
            - pkg-install
