name: Clear GitHub runner caches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs once a week (Sunday midnight)

jobs:
  clear:
    name: Clear caches
    runs-on: ubuntu-latest
    steps:
    - uses: MyAlbum/purge-cache@v2
      with:
        max-age: 604800 # Caches older than 7 days are deleted
